# Generated by Django 3.2.3 on 2021-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20210605_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('articleId', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
